name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Create .env for DummyJSON tests
        run: |
          cat > .env <<EOF
          BASE_URL=https://dummyjson.com
          USERNAME=emilys
          PASSWORD=emilyspass
          EOF

      - name: Start mock server
        run: npm run start:mock &

      - name: Wait for mock server to be ready
        run: |
          for i in {1..10}; do
            curl -s http://127.0.0.1:3000/auth/login > /dev/null && break
            echo "Waiting for mock server..." && sleep 1
          done

      - name: Run all API tests
        run: npx playwright test

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
